// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiscoveryService finds peer Light devices on the local network via UDP beacons.
 * 
 * Design (deliberately simple + debuggable, unlike the old mDNS approach that
 * "found nothing"):
 *   - ONE wildcard UDP receiver bound to 0.0.0.0:<discoveryPort> captures beacons
 *     from every interface.
 *   - N per-interface directed-broadcast senders (plus 255.255.255.255 and the
 *     loopback address) ALWAYS broadcast our beacon. These are not fallbacks that
 *     trigger only on error — they all run unconditionally.
 *   - The device ID is a persisted crypto/rand UUID, never derived from a cert,
 *     so beacons never accidentally self-filter.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Diagnostics(): $CancellablePromise<$models.Diagnostics> {
    return $Call.ByID(4146114391).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDevicePairingCode(): $CancellablePromise<string> {
    return $Call.ByID(3930434438);
}

export function GetDevices(): $CancellablePromise<$models.Device[]> {
    return $Call.ByID(3036480426).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * LocalEndpoint returns this device's transfer address as host:port (used for QR).
 */
export function LocalEndpoint(): $CancellablePromise<string> {
    return $Call.ByID(2154841241);
}

export function PairByCode(code: string): $CancellablePromise<$models.Device | null> {
    return $Call.ByID(3759008805, code).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2953749430, app);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3889309759);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3127683269);
}

// Private type creation functions
const $$createType0 = $models.Diagnostics.createFrom;
const $$createType1 = $models.Device.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Nullable($$createType1);
