// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiscoveryService finds peer Light devices on the local network via UDP beacons.
 * 
 * Design (deliberately simple + debuggable, unlike the old mDNS approach that
 * "found nothing"):
 *   - ONE wildcard UDP receiver bound to 0.0.0.0:<discoveryPort> captures beacons
 *     from every interface.
 *   - N per-interface directed-broadcast senders (plus 255.255.255.255 and the
 *     loopback address) ALWAYS broadcast our beacon. These are not fallbacks that
 *     trigger only on error — they all run unconditionally.
 *   - The device ID is a persisted crypto/rand UUID, never derived from a cert,
 *     so beacons never accidentally self-filter.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConnectWifiDirect forms a P2P group with the peer and records its transfer
 * address in the device table so the existing HTTP/QUIC path can use it. It
 * falls back to returning ErrWifiDirectUnsupported when the platform cannot host
 * a link, leaving normal LAN discovery untouched.
 */
export function ConnectWifiDirect(peerID: string): $CancellablePromise<string> {
    return $Call.ByID(433749557, peerID);
}

export function Diagnostics(): $CancellablePromise<$models.Diagnostics> {
    return $Call.ByID(4146114391).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetDevicePairingCode(): $CancellablePromise<string> {
    return $Call.ByID(3930434438);
}

export function GetDevices(): $CancellablePromise<$models.Device[]> {
    return $Call.ByID(3036480426).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * LocalEndpoint returns this device's transfer address as host:port (used for QR).
 */
export function LocalEndpoint(): $CancellablePromise<string> {
    return $Call.ByID(2154841241);
}

export function PairByCode(code: string): $CancellablePromise<$models.Device | null> {
    return $Call.ByID(3759008805, code).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Refresh reopens discovery senders so a changed Wi-Fi or Ethernet interface
 * is picked up immediately, then announces this device on the active LANs.
 */
export function Refresh(): $CancellablePromise<$models.Device[]> {
    return $Call.ByID(1505301652).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2953749430, app);
}

/**
 * SetWifiDirectManager injects the platform Wi-Fi Direct backend. It is created
 * lazily by WifiDirectPeers/ConnectWifiDirect when the setting is enabled, but
 * can also be wired explicitly at startup.
 */
export function SetWifiDirectManager(m: $models.WifiDirectManager): $CancellablePromise<void> {
    return $Call.ByID(2341060054, m);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3889309759);
}

export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(3127683269);
}

/**
 * WifiDirectPeers returns nearby devices discovered via Wi-Fi Direct, or nil when
 * the feature is disabled or unsupported. The transfer stack reuses the existing
 * device table, so no transport changes are needed.
 */
export function WifiDirectPeers(): $CancellablePromise<$models.WifiDirectPeer[]> {
    return $Call.ByID(309302474).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Diagnostics.createFrom;
const $$createType1 = $models.Device.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Nullable($$createType1);
const $$createType4 = $models.WifiDirectPeer.createFrom;
const $$createType5 = $Create.Array($$createType4);
