// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileTransferService runs a per-device HTTP server that receives files and
 * drives outgoing uploads to peers.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcceptReceive accepts an inbound batch. selected is the subset of filenames the
 * receiver consented to; a nil slice means the whole batch, which is what an
 * older client (and auto-accept) sends.
 */
export function AcceptReceive(transferID: string, selected: string[]): $CancellablePromise<void> {
    return $Call.ByID(825001203, transferID, selected);
}

export function CancelTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3958490703, id);
}

export function PauseTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3301912675, id);
}

export function RejectReceive(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(3036035682, transferID);
}

export function RestartServer(): $CancellablePromise<void> {
    return $Call.ByID(2171377134);
}

export function ResumeTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3002209458, id);
}

export function SendFiles(req: $models.TransferRequest): $CancellablePromise<void> {
    return $Call.ByID(815122251, req);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3174908325, app);
}

export function StartServer(): $CancellablePromise<void> {
    return $Call.ByID(3711350801);
}

/**
 * StatFiles resolves the display name and size of send-side paths without
 * reading their contents. The Bulk Share picker uses it to show a running total
 * for a staged selection before anything is sent; the native pickers only hand
 * back paths, so there is no other way to learn the sizes.
 */
export function StatFiles(paths: string[]): $CancellablePromise<$models.SendFileStat[]> {
    return $Call.ByID(2955848779, paths).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StopServer(): $CancellablePromise<void> {
    return $Call.ByID(2089537913);
}

// Private type creation functions
const $$createType0 = $models.SendFileStat.createFrom;
const $$createType1 = $Create.Array($$createType0);
