// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileTransferService runs a per-device HTTP server that receives files and
 * drives outgoing uploads to peers.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AcceptReceive(transferID: string, $1: string[]): $CancellablePromise<void> {
    return $Call.ByID(825001203, transferID, $1);
}

export function CancelTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3958490703, id);
}

export function PauseTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3301912675, id);
}

export function RejectReceive(transferID: string): $CancellablePromise<void> {
    return $Call.ByID(3036035682, transferID);
}

export function RestartServer(): $CancellablePromise<void> {
    return $Call.ByID(2171377134);
}

export function ResumeTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3002209458, id);
}

export function SendFiles(req: $models.TransferRequest): $CancellablePromise<void> {
    return $Call.ByID(815122251, req);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3174908325, app);
}

export function StartServer(): $CancellablePromise<void> {
    return $Call.ByID(3711350801);
}

export function StopServer(): $CancellablePromise<void> {
    return $Call.ByID(2089537913);
}
