// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Device {
    "id": string;
    "name": string;
    "type": DeviceType;

    /**
     * host:port of the peer's transfer server
     */
    "address": string;

    /**
     * pairing code last advertised by this peer
     */
    "code": string;
    "lastSeen": Date;

    /** Creates a new Device instance. */
    constructor($$source: Partial<Device> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = DeviceType.$zero;
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("lastSeen" in $$source)) {
            this["lastSeen"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     */
    static createFrom($$source: any = {}): Device {
        const $$createField5_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lastSeen" in $$parsedSource) {
            $$parsedSource["lastSeen"] = $$createField5_0($$parsedSource["lastSeen"]);
        }
        return new Device($$parsedSource as Partial<Device>);
    }
}

export enum DeviceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DeviceTypeDesktop = "desktop",
    DeviceTypeMobile = "mobile",
};

export class Diagnostics {
    "myId": string;
    "listening": boolean;
    "devices": number;
    "interfaces": number;
    "senders": number;
    "lastError": string;

    /** Creates a new Diagnostics instance. */
    constructor($$source: Partial<Diagnostics> = {}) {
        if (!("myId" in $$source)) {
            this["myId"] = "";
        }
        if (!("listening" in $$source)) {
            this["listening"] = false;
        }
        if (!("devices" in $$source)) {
            this["devices"] = 0;
        }
        if (!("interfaces" in $$source)) {
            this["interfaces"] = 0;
        }
        if (!("senders" in $$source)) {
            this["senders"] = 0;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagnostics instance from a string or object.
     */
    static createFrom($$source: any = {}): Diagnostics {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Diagnostics($$parsedSource as Partial<Diagnostics>);
    }
}

export class Settings {
    "deviceName": string;
    "port": number;
    "downloadDir": string;
    "autoAccept": boolean;
    "theme": string;
    "enableEncryption": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("deviceName" in $$source)) {
            this["deviceName"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("downloadDir" in $$source)) {
            this["downloadDir"] = "";
        }
        if (!("autoAccept" in $$source)) {
            this["autoAccept"] = false;
        }
        if (!("theme" in $$source)) {
            this["theme"] = "";
        }
        if (!("enableEncryption" in $$source)) {
            this["enableEncryption"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class Transfer {
    "id": string;
    "filename": string;
    "size": number;
    "transferred": number;
    "percent": number;

    /**
     * bytes/sec
     */
    "speed": number;
    "status": TransferStatus;
    "error"?: string;
    "filePath"?: string;
    "checksum"?: string;
    "startedAt": Date;
    "completedAt"?: Date | null;

    /** Creates a new Transfer instance. */
    constructor($$source: Partial<Transfer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("transferred" in $$source)) {
            this["transferred"] = 0;
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = TransferStatus.$zero;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Transfer instance from a string or object.
     */
    static createFrom($$source: any = {}): Transfer {
        const $$createField10_0 = $Create.DateFromTime;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("startedAt" in $$parsedSource) {
            $$parsedSource["startedAt"] = $$createField10_0($$parsedSource["startedAt"]);
        }
        if ("completedAt" in $$parsedSource) {
            $$parsedSource["completedAt"] = $$createField11_0($$parsedSource["completedAt"]);
        }
        return new Transfer($$parsedSource as Partial<Transfer>);
    }
}

export class TransferRequest {
    "deviceId": string;
    "deviceAddr": string;
    "filePaths": string[];

    /** Creates a new TransferRequest instance. */
    constructor($$source: Partial<TransferRequest> = {}) {
        if (!("deviceId" in $$source)) {
            this["deviceId"] = "";
        }
        if (!("deviceAddr" in $$source)) {
            this["deviceAddr"] = "";
        }
        if (!("filePaths" in $$source)) {
            this["filePaths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferRequest {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filePaths" in $$parsedSource) {
            $$parsedSource["filePaths"] = $$createField2_0($$parsedSource["filePaths"]);
        }
        return new TransferRequest($$parsedSource as Partial<TransferRequest>);
    }
}

export enum TransferStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusPending = "pending",
    StatusActive = "active",
    StatusPaused = "paused",
    StatusCompleted = "completed",
    StatusFailed = "failed",
    StatusCancelled = "cancelled",
};

// Private type creation functions
const $$createType0 = $Create.Nullable($Create.DateFromTime);
const $$createType1 = $Create.Array($Create.Any);
