// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QRCodeService generates QR codes for device pairing. The QR encodes a JSON
 * connection ticket {id,name,address,port,type} that the peer scans to connect
 * (works cross-subnet, where UDP discovery alone cannot reach).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GenerateDeviceQRCode(name: string, id: string, address: string, port: string, dtype: $models.DeviceType): $CancellablePromise<string> {
    return $Call.ByID(488096894, name, id, address, port, dtype);
}

export function GenerateQRCodeFromText(text: string): $CancellablePromise<string> {
    return $Call.ByID(3498638263, text);
}

export function GetDevicePairingCode(): $CancellablePromise<string> {
    return $Call.ByID(3477716910);
}

export function GetDeviceQRCode(): $CancellablePromise<string> {
    return $Call.ByID(3781943063);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(2979617870, app);
}
