// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService owns the persisted app configuration and a stable device ID.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeviceID(): $CancellablePromise<string> {
    return $Call.ByID(4108505061);
}

export function GetDefaultDownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(2814541946);
}

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(1940451047).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(4073219317, app);
}

export function SetAutoAccept(b: boolean): $CancellablePromise<void> {
    return $Call.ByID(2732820389, b);
}

export function SetDeviceName(n: string): $CancellablePromise<void> {
    return $Call.ByID(4047234403, n);
}

export function SetDownloadDir(d: string): $CancellablePromise<void> {
    return $Call.ByID(683392989, d);
}

export function SetDownloadDirUri(u: string): $CancellablePromise<void> {
    return $Call.ByID(1072180501, u);
}

export function SetPort(p: number): $CancellablePromise<void> {
    return $Call.ByID(3728637401, p);
}

export function SetTheme(t: string): $CancellablePromise<void> {
    return $Call.ByID(344117895, t);
}

export function UpdateSettings(s2: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(1137475426, s2);
}

/**
 * WifiDirectSupported reports whether the current platform can host a Wi-Fi
 * Direct link. macOS cannot, so the UI hides the toggle there.
 */
export function WifiDirectSupported(): $CancellablePromise<boolean> {
    return $Call.ByID(1948522520);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
