// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TransferManager tracks in-flight transfers and persists completed/failed/
 * cancelled transfers to ~/.light/history.json (JSON — deliberately simpler than
 * SQLite to avoid any CGO/mobile cross-compile risk).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Cancel(id: string): $CancellablePromise<void> {
    return $Call.ByID(1357923062, id);
}

export function ClearHistory(): $CancellablePromise<void> {
    return $Call.ByID(776463387);
}

export function Complete(id: string, filePath: string, checksum: string): $CancellablePromise<void> {
    return $Call.ByID(4054080763, id, filePath, checksum);
}

export function Fail(id: string, errMsg: string): $CancellablePromise<void> {
    return $Call.ByID(2615272616, id, errMsg);
}

export function GetAll(): $CancellablePromise<($models.Transfer | null)[]> {
    return $Call.ByID(1966699715).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetHistory(limit: number): $CancellablePromise<($models.Transfer | null)[]> {
    return $Call.ByID(2348828296, limit).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Pause(id: string): $CancellablePromise<void> {
    return $Call.ByID(3633932446, id);
}

export function RecordTransfer(t: $models.Transfer | null): $CancellablePromise<void> {
    return $Call.ByID(1864442034, t);
}

export function Resume(id: string): $CancellablePromise<void> {
    return $Call.ByID(2343739463, id);
}

export function UpdateProgress(id: string, transferred: number, speed: number): $CancellablePromise<void> {
    return $Call.ByID(1080230454, id, transferred, speed);
}

// Private type creation functions
const $$createType0 = $models.Transfer.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
