// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService adapts the Wails updater to Light's main window. A separate
 * service keeps the generated frontend API small and lets Android show release
 * information without attempting an impossible in-place APK replacement.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CanInstall(): $CancellablePromise<boolean> {
    return $Call.ByID(2612485187);
}

/**
 * CheckForUpdates checks the stable GitHub release channel. The updater emits
 * its lifecycle events, while this return value is convenient for first paint.
 */
export function CheckForUpdates(): $CancellablePromise<$models.UpdateInfo> {
    return $Call.ByID(1303360817).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(1043011477);
}

/**
 * DownloadAndInstall downloads the release found by CheckForUpdates and
 * stages it after Wails verifies its checksum.
 */
export function DownloadAndInstall(): $CancellablePromise<void> {
    return $Call.ByID(972529354);
}

export function IsSupported(): $CancellablePromise<boolean> {
    return $Call.ByID(3144024324);
}

/**
 * Restart applies the staged artifact through Wails' detached helper and
 * relaunches the updated executable.
 */
export function Restart(): $CancellablePromise<void> {
    return $Call.ByID(1456334765);
}

/**
 * SetApp configures the Wails GitHub provider once the application exists.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(713809641, app);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
